<a href="https://colab.research.google.com/github/cghv94/introduccion-a-python/blob/main/Introducci%C3%B3n_a_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introducción a NumPy**
## **Facultad de Economía, UNAM**
### **Profesor: Cesar Hernández**

**NumPy (Numerical Python)** es una librería de Python que permite realizar arreglos con vectores y matrices además de diversas funciones matemáticas.

In [1]:
 # Para importar la librería
 import numpy as np

## **Listas**

Primero aprenderemos a trabajar con objetos de clase *list*. 

* Para crear una lista:



In [2]:
lista = [12, 39, 41, 7]
lista

[12, 39, 41, 7]

* Para conocer qué tipo de objeto es *lista*:



In [3]:
print(type(lista))

<class 'list'>


* Para unir el contenido de dos listas (no se pueden hacer operaciones matemáticas con listas):

In [4]:
print(lista + lista)

[12, 39, 41, 7, 12, 39, 41, 7]


## **Vectores**

Podemos convertir los objetos typo *list* a objetos tipo *array* con la ayuda de **NumPy** y la función *np.array*. 

* Para transformar nuestro objeto *lista* a un *vector*:



In [5]:
vector = np.array(lista)
vector

array([12, 39, 41,  7])

* Para saber qué tipo de objeto es *vector*:

In [6]:
print(type(vector))

<class 'numpy.ndarray'>


* Para saber el número de elementos del *vector*:

In [7]:
vector.size

4

* Para obtener el menor valor dentro del *vector*:

In [8]:
vector.min()

7

* Para obtener el mayor valor dentro del *vector*: 


In [9]:
vector.max()

41

* Para ordenar los elementos del *vector* de menor a mayor

In [10]:
vector.sort()
vector

array([ 7, 12, 39, 41])

* Para sumar los elementos de un *vector*:

In [11]:
vector.sum()

99

## **Operaciones con vectores**

Podemos hacer algunas operaciones matemáticas con objetos tipo *np.array*. 

* Primero crearemos el *vector_a* y el *vector _b*:


In [12]:
vector_a = np.array([ -3, -1, 2, 4])
vector_b = np.array([ -2, 0, 1, 3])
print(vector_a, vector_b)

[-3 -1  2  4] [-2  0  1  3]


* Para sumar dos vectores:

In [13]:
print(vector_a + vector_b)

[-5 -1  3  7]


* Para restar dos vectores:

In [14]:
print(vector_b - vector_a)

[ 1  1 -1 -1]


* Para multiplicar un vector por un escalar:

In [15]:
print(vector_b * 5)

[-10   0   5  15]


* Para multiplicar dos vectores:

In [16]:
print(vector_a * vector_b)

[ 6  0  2 12]


* Para dividir dos vectores:

In [17]:
print(vector_b / vector_a)

[ 0.66666667 -0.          0.5         0.75      ]


* Para redondear los valores de un vector:

In [18]:
division = vector_b / vector_a
division.round()

array([ 1., -0.,  0.,  1.])

## **Matrices y operaciones con matrices**

Podemos hacer matrices si integramos varias listas a onjetos de tipo *np.array*. 

* Primero crearemos los objetos *vector_c*, *vector_d* y *vector_e* y después los integraremos en un objeto tipo *np.array*:


In [19]:
vector_c = [ 15, 21, 45]
vector_d = [ 63, 30, 29]
vector_e = [ 36, 54, 71]
matriz = np.array([vector_c, vector_d, vector_e])
matriz

array([[15, 21, 45],
       [63, 30, 29],
       [36, 54, 71]])

* Para sumar dos matrices:

In [20]:
print(matriz + matriz)

[[ 30  42  90]
 [126  60  58]
 [ 72 108 142]]


* Para multiplicar dos matrices:

In [21]:
print(matriz * matriz)

[[ 225  441 2025]
 [3969  900  841]
 [1296 2916 5041]]


* Para dividir dos matrices:

In [22]:
print(matriz / matriz)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


* Para obtener el determinante de una matriz:

In [23]:
np.linalg.det(matriz)

40940.99999999999

* Para obtener la matriz inversa:

In [24]:
np.linalg.inv(matriz)

array([[ 0.01377592,  0.02293544, -0.01809922],
       [-0.08375467, -0.01355609,  0.05862094],
       [ 0.05671576, -0.00131897, -0.02132337]])

## **Material adicional**

**NumPy** es una librería de código abierto que cuenta con una gran comunidad por detrás. Podrás encontrar diversos recursos en línea que te ayudarán a continuar con tu aprendizaje. A continuación te dejamos algunas sugerencias de recursos en línea con los que podrás reforzar tu aprendizaje:

* [Learn NumPy in 5 minutes](https://www.youtube.com/watch?v=xECXZ3tyONo)
* [Introduction to NumPy](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.00-Introduction-to-NumPy.ipynb)
*[Learn NumPy](https://www.tutorialspoint.com/numpy/)



## **Créditos**

Esta obra fue generada mediante en Colaboratory el 27 de enero de 2020 y forma parte de las actividades realizadas en las materias de [Matemáticas I y Taller III](https://mateytaller.github.io/), [Facultad de Economía, UNAM](http://economia.unam.mx/).

<p>Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">licencia de Creative Commons Reconocimiento-NoComercial-CompartirIgual 4.0 Internacional. </a>Creative Commons (CC).<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licencia de Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a></p>